### PR TITLE
[refactor] feature extraction script upgrade

### PR DESCRIPTION
**Pull request by ytsheng**
* Update the comment to point to the correct maskrcnn-benchmark. There are many on github that is available. This one is the correct one to use.
* Added the X152 model
* Tested that both models can be loaded with the updated repo.

### CODE REVIEW

**Comment by vedanuj** [comment]
We should also to upload the latest models for X152 and update the comment, should be good to keep an option to use both the current(X101) as well as the X152 models. cc @apsdehal what do you think?

**Comment by apsdehal** [comment]
Yes, that would be good addition as part of this PR.

**Review by vedanuj — COMMENTED** [review]
Can we add an argument param that can help specify which model user wants to use? Also make sure both the models can be loaded with the updated repo (we only tested the X-152 model in that).

**Comment by vedanuj** [comment]
Thanks for updating. Looks good! Can you import this to phabricator?

**Review by vedanuj — APPROVED** [review]

**Pull request closed without merging**
